language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t asjadjawed/docker-react -f Dockerfile.dev .

# https://create-react-app.dev/docs/running-tests/#linux-macos-bash
script:
  - docker run -e CI=true asjadjawed/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-978387451341"
  bucket_path: "docker-react" # initially it is same as application name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
